### ISSUE TITLE
how to prepare the taxonomy files?

### ISSUE THREAD

**Issue by ZhangC2** [kibok90/cvpr2018-hnd#3]
Thank you for the code relese. Could you give more deatils of the taxonomy build?

**Comment by kibok90** [comment]
Hierarchical novelty detection requires a taxonomy of class labels, so they should be built before training. You can download [the pre-built taxonomy](https://drive.google.com/uc?export=download&id=1p_-Yq3hd9ITrAveafj3sC00VCN3VJlE1) and see what components are. Basically, ancestor-descendant relationship and distance between classes in the taxonomy would be the essential information, and they are summarized in many different forms for efficient training.

You can also check [`build_taxonomy.py`](https://github.com/kibok90/cvpr2018-hnd/blob/master/build_taxonomy.py) to see how they are obtained.
