### ISSUE TITLE
Top-down method objective function

### ISSUE THREAD

**Issue by a121529392** [kibok90/cvpr2018-hnd#5]
Hi ,
The objective function of Top-down method is above , but I can not find the code of KL divergence .
![image](https://user-images.githubusercontent.com/25115487/127606171-18dd4edf-0b80-43c5-adcb-98bdad13fe7c.png)
This is the loss of TDloss
![image](https://user-images.githubusercontent.com/25115487/127606313-e7c1443c-9326-487e-b670-e810084cb6ed.png)

**Comment by kibok90** [comment]
Hi,
The second term is the KL divergence between the uniform distribution and the probability, which can be simplified as in
https://github.com/kibok90/cvpr2018-hnd/blob/master/models.py#L199-L203
