### ISSUE TITLE
Getting error in truncated_normal

### ISSUE THREAD

**Issue by spandan12** [kibok90/cvpr2018-hnd#6]
I am getting error in `trucated_normal`  in models.py. The exact error that I am getting is for the command
`sh scripts/train.sh awa2 loo`
 
![image](https://user-images.githubusercontent.com/33442589/204618385-29c54df9-f409-44aa-b18b-a51dc7523656.png)

For resolving the issue, I tried putting the value of mean as 0 as:

```
model.weight.data[truncate_me] = torch.normal(std=std*torch.ones(truncate_me.sum()), mean = 0)
```

It gives me the result as:

```
test;  161.208 s
bias:  2.9339; acc known: 50.00; novel: 49.46; auc  : 43.13;
```

And upon running the training for the same dataset for td+loo as 

` sh scripts/train.sh awa2 td+loo`
I am getting the result as:

```
test;  100.029 s
bias:  0.8533; acc known: 50.00; novel: 44.47; auc  : 34.43;
```
However, the reported result in the paper for awa2 is

LOO: 
Novel: 50.00 AUC: 43.63
TD+LOO:
Novel: 53.57, AUC: 46.77

The metrics for LOO look similar. But, for TD+LOO, the metrics decrease.

1. Could you please help me with the initial error for the mean value that I am receiving ? 
2. Also, it would be helpful if you could describe what the elements mean in building taxonomy? The elements are 
'wnids_leaf', 'wnids', 'wnids_raw', 'wnid_groups', 'wnid_to_group', 'wnid_to_index', 'wnid_root', 'wnid_parents', 'wnid_children', 'wnid_ancestors', 'wnid_descendants', 'wnid_ancestors_hop', 'wnid_descendants_hop', 'wnid_depths', 'wnid_heights', 'is_parent_mat', 'is_ancestor_mat', 'root', 'parents', 'children', 'ancestors', 'descendants', 'ancestors_hop', 'descendants_hop', 'heights', 'num_children', 'ch_slice', 'wnids_novel', 'wnid_ancestors_novel', 'wnid_novel_to_raw', 'wnid_novel_to_wnid_known', 'wnid_novel_to_known', 'label_enum', 'label_hnd', 'label_zsl'
Some of the elements make sense like wnids: wordnet ids, wnids_leaf: wordnet_ids leaf, But some of the elements don't make sense just by looking at their name. It would help in better understanding of the code.

**Comment by kibok90** [comment]
1. Please first make sure you matched the version of all necessary packages; in particular, this code is implemented with PyTorch 0.3.0.post4, which I believe is not so compatible with the latest version.

2. About vars for taxomony, you can take a look at https://github.com/kibok90/cvpr2018-hnd/blob/master/build_taxonomy.py to understand the meaning of them. There are too many vars so I cannot describe all of them in detail. Below is a description of a part of them:

wnid: wordnet id
raw: raw items without any processing
group: I grouped wnids if they are not meaningful for hierarchical classification, e.g., if a parent has one child, they are grouped.
index: class index
hop: distance in the graph
ch_slice: index slices for each superclass
enum: enumerate
hnd: hierarchical novelty detection
zsl: zero-shot learning
