### ISSUE TITLE
Request for Update

### ISSUE THREAD

**Issue by ZY123-GOOD** [kibok90/cvpr2018-hnd#7]
I am very interested in your work. Now, I would like to attempt to reproduce the code. Could you please update the link related to the features, or kindly advise how to obtain the features for the CUB dataset?

**Comment by kibok90** [comment]
I just confirmed that the link for downloading AWA and CUB features still works, so you can download and play with it. There might be a warning about unsecure connection but you can simply ignore it.
The link is from a zero-shot learning paper (https://arxiv.org/abs/1703.04394), and the features are extracted using ResNet-101 pretrained on ImageNet-1k.

**Comment by ZY123-GOOD** [comment]
> I just confirmed that the link for downloading AWA and CUB features still works, so you can download and play with it. There might be a warning about unsecure connection but you can simply ignore it. The link is from a zero-shot learning paper (https://arxiv.org/abs/1703.04394), and the features are extracted using ResNet-101 pretrained on ImageNet-1k.

Thank you for your prompt response. Does the line identity = Identity() in the test.py file imply that during testing, no pre-trained multi-class head is utilized? Should I replace this with "TD_-1_1e+00_0e+00_cw_1e-02_1e-02_model_427.pth" instead?

**Comment by ZY123-GOOD** [comment]
> I just confirmed that the link for downloading AWA and CUB features still works, so you can download and play with it. There might be a warning about unsecure connection but you can simply ignore it. The link is from a zero-shot learning paper (https://arxiv.org/abs/1703.04394), and the features are extracted using ResNet-101 pretrained on ImageNet-1k.

For example, I trained the model using this command ”sh scripts/train.sh cub td“, how should I proceed to test it? Could you kindly provide me with the command for testing? Your assistance is greatly appreciated, wishing you all the best.

**Comment by ZY123-GOOD** [comment]
> I just confirmed that the link for downloading AWA and CUB features still works, so you can download and play with it. There might be a warning about unsecure connection but you can simply ignore it. The link is from a zero-shot learning paper (https://arxiv.org/abs/1703.04394), and the features are extracted using ResNet-101 pretrained on ImageNet-1k.

I hope to test the trained model on an image.

**Comment by kibok90** [comment]
> Thank you for your prompt response. Does the line identity = Identity() in the test.py file imply that during testing, no pre-trained multi-class head is utilized? Should I replace this with "TD_-1_1e+00_0e+00_cw_1e-02_1e-02_model_427.pth" instead?

The purpose of this repo is to reproduce the results reported in the paper without any changes, so please take the code as it is if that is your purpose.

> For example, I trained the model using this command ”sh scripts/train.sh cub td“, how should I proceed to test it? Could you kindly provide me with the command for testing? Your assistance is greatly appreciated, wishing you all the best.

You can find the answer in the script and code. The training code gets `--test` to run testing after training. If a checkpoint is found, the training code will either 1) resume training or 2) perform testing if training is already done.

> I hope to test the trained model on an image.

It seems I didn't provide an API to test a single image. You can build a data loader with the image you want to test and plug in the data loader to the test function.

**Comment by ZY123-GOOD** [comment]
> > Thank you for your prompt response. Does the line identity = Identity() in the test.py file imply that during testing, no pre-trained multi-class head is utilized? Should I replace this with "TD_-1_1e+00_0e+00_cw_1e-02_1e-02_model_427.pth" instead?
> 
> The purpose of this repo is to reproduce the results reported in the paper without any changes, so please take the code as it is if that is your purpose.
> 
> > For example, I trained the model using this command ”sh scripts/train.sh cub td“, how should I proceed to test it? Could you kindly provide me with the command for testing? Your assistance is greatly appreciated, wishing you all the best.
> 
> You can find the answer in the script and code. The training code gets `--test` to run testing after training. If a checkpoint is found, the training code will either 1) resume training or 2) perform testing if training is already done.
> 
> > I hope to test the trained model on an image.
> 
> It seems I didn't provide an API to test a single image. You can build a data loader with the image you want to test and plug in the data loader to the test function.

Thank you for your patient and detailed response. As a beginner, I am deeply grateful, and my question has been fully resolved.
